# Generated by Django 2.2.5 on 2019-09-06 18:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 6, 18, 28, 56, 473192, tzinfo=utc), editable=False),
        ),
    ]
